---
title: "git_01"
author: "Jarrod Harris"
date: "Summer 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
  
’Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
“Beware the Jabberwock, my son!  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
  
<<<<<<< HEAD
When I go up through the mowing field,  
The headless aftermath,  
Smooth-laid like thatch with the heavy   dew,  
Half closes the garden path.  
And when I come to the garden ground,  
  
=======
When I go up through the mowing field,    
The headless aftermath,  
Smooth-laid like thatch with the heavy   dew,   
Half closes the garden path.      
And when I come to the garden ground,    
   

>>>>>>> verse2
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
  
“The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  
  
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
“It’s very rude of him,” she said,  
“To come and spoil the fun.”  
<<<<<<< HEAD
    
=======
  

>>>>>>> verse3
## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
  
The animal I really dig,  
Above all others is the pig.  
Pigs are noble. Pigs are clever,  
Pigs are courteous. However,  
Now and then, to break this rule,  
One meets a pig who is a fool.  
What, for example, would you say,  
If strolling through the woods one day,  
Right there in front of you you saw  
A pig who’d built his house of STRAW?  
The Wolf who saw it licked his lips,  
And said, ‘That pig has had his chips.’  
‘Little pig, little pig, let me come in!’  
‘No, no, by the hairs on my   chinny-chin-chin!’  
‘Then I’ll huff and I’ll puff and I’ll   blow your house in!’  
  
The little pig began to pray,  
But Wolfie blew his house away.  
He shouted, ‘Bacon, pork and ham!  
Oh, what a lucky Wolf I am!’  
And though he ate the pig quite fast,  
He carefully kept the tail till last.  
Wolf wandered on, a trifle bloated.  
Surprise, surprise, for soon he noted  
Another little house for pigs,  
And this one had been built of TWIGS!  